// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ztkhgckgylfkcixgxikf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0a2hnY2tneWxma2NpeGd4aWtmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4OTE2NjMsImV4cCI6MjA2OTQ2NzY2M30.X7BDdepsOWKWhX3tdA-cX7y3KSW1K-xIWLstH4Q5-Ho";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});